# workflow de la rama release
name: release branch ci, deploy aws

on:
  push:
    branches:
      - "release/**"
  create:
      branches:
        - "release/**"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar version node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Ejecutar tests
        run: npm test

      - name: Configurar credenciales aws
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Empaquerar codigo lambda
        run: |
          zip -r ../lambda.zip .

      - name: Subir lambda a S3
        run: |
          aws s3 cp ../lambda.zip s3://${{ secrets.S3_BUCKET_NAME }}/lambda.zip

      - name: Ejecutar cloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-lambda.yaml \
            --stack-name create-lambda-aws \
            --capabilities CAPABILITY_IAM \
            --parameters-overrides S3BucketName=${{ secrets.S3_BUCKET_NAME }} S3Key=lambda.zip
